name: BuildAndTest

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: bitnami/mysql:8.0
        env:
          MYSQL_USER: sugar_talk
          MYSQL_PASSWORD: 123456
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
        ports:
          - 3306/tcp
        options: >-
          --health-cmd="mysqladmin ping" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore src/SugarTalk.sln
    - name: Build
      run: dotnet build src/SugarTalk.sln --no-restore
    - name: Test
      run: dotnet test src/SugarTalk.sln --no-build --verbosity normal
