name: Integration and unit tests

on:
  push:
    branches: [ ]
  pull_request:
    branches: [ ]

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.x' ]
        mongodb-version: [ 4.4 ]
    steps:
      - name: Prepare Environment
        run: sudo bash -c "echo '127.0.0.1      mongoserver' >> /etc/hosts"
      - uses: actions/checkout@v2
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore src/SugarTalk.sln
      - name: Build
        run: dotnet build src/SugarTalk.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test src/SugarTalk.sln --no-restore --verbosity normal
